### ISSUE TITLE
Environment variables are not interpolated

### ISSUE THREAD

**Issue by jacobisaliveandwell** [asyncon/setuptools-pipfile#1]
When a `Pipfile` `[[source]]` section includes an environment variable, this library is not resolving that variable to it's value, which results in `install_requires` and `test_requires` to break with the following error:

```plain
error in example_project setup command: 'tests_require' must be a string or list of strings containing valid project/version requirement specifiers; Invalid URL: ${MY_CUSTOM_PIP_URL}/my-awesome-package/
```

Reference: https://pipenv-fork.readthedocs.io/en/latest/advanced.html#injecting-credentials-into-pipfiles-via-environment-variables

**Comment by asyncon** [comment]
Version 0.3.1 which fixes this issue has been released.

**Comment by jacobisaliveandwell** [comment]
@asyncon Thank you so much for jumping on this so quickly!
