### ISSUE TITLE
Provide option to read from Pipfile.lock instead of Pipfile

### ISSUE THREAD

**Issue by hugochinchilla** [asyncon/setuptools-pipfile#3]
To avoid surprises it would be "more correct" to read dependencies from Pipfile.lock than from Pipfile.

**Comment by asyncon** [comment]
There are two competing ideas surrounding this. On one hand locking is good for repeatable CI/CD processes and application deployment. On the other this package exists to enable the development of libraries with pipenv without duplicating the dependency metadata.

Libraries typically do not need locked versions as this tends to introduce fragility. When it is required it is usually managed manually in a manner that results in a declared dependency requirement such as [fastapi depending on a specific starlette version](https://github.com/tiangolo/fastapi/blob/f67b19f0f73ebdca01775b8c7e531e51b9cecfae/pyproject.toml#L41).

In the case of proprietary dependency development, locking can seem like a simple solution to the issue of ensuring all testing is done with the exact same dependency versions throughout the entire stack while being able to use the same tooling to easily update dependency versions. 

However two intermediate dependencies which both require the same shared dependency can result in a version mismatch.

```mermaid
flowchart LR
	subgraph Dependency-Graph
	  direction TB
	  App-->Component-X
	  App-->Component-Y
	  Component-X-->Shared-Dependency
	  Component-Y-->Shared-Dependency
	end
	subgraph Lock-Graph-Conflict
	  direction TB
	  App-Unlockable-->Component-X-Locked
	  App-Unlockable-->Component-Y-Locked
	  Component-X-Locked-->Shared-Dependency-1.0.0
	  Component-Y-Locked-->Shared-Dependency-1.0.1
	end
	Dependency-Graph-->Lock-Graph-Conflict
```

This would then require introducing a process or system to ensure the dependency versions are kept in-sync which can introduce significant overhead to the development process. Systems that can do this (such as [pants](https://www.pantsbuild.org/)) are generally referred to as monorepo tools.

The resistance to this idea comes from wanting to avoid the temptation to introduce that fragility into a pipeline by not providing the option in the first place.

This is not a definite no however a better use case is required than simply saying locking is more correct as this conflicts with this package's core purpose.
