### ISSUE TITLE
Use Pipfile.lock instead of Pipfile

### ISSUE THREAD

**Issue by zeevro** [asyncon/setuptools-pipfile#5]
This would be very useful to me if it could get the dependencies from the `Pipfile.lock` file. Currently, there's no support for actually relying on locked dependency versions so I don't see how it's better than putting the dependencies directly in the `pyproject.toml` file.

**Comment by asyncon** [comment]
Pipenv doesn't manage `pyproject.toml`. If it did you would no longer need this package.

If a valid use case for this feature is described then it will be considered. 

Otherwise the answer given in https://github.com/asyncon/setuptools-pipfile/issues/3#issuecomment-1287982133 remains correct.

**Comment by asyncon** [comment]
Pipenv doesn't manage `pyproject.toml`. If it did you would no longer need this package.

If a valid use case for this feature is described then it will be considered. 

Otherwise the answer given in https://github.com/asyncon/setuptools-pipfile/issues/3#issuecomment-1287982133 remains correct.
